---
# JENKINS
- hosts: DevOps
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: Add the Jenkins Repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import a Key file from Jenkins-ci
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key 

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: install java
      shell: amazon-linux-extras install java-openjdk11 -y

    - name: install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Start Jenkins
      ansible.builtin.systemd:
        enabled: yes
        name: jenkins
        state: started

    - name: Change Jenkins port
      lineinfile:
        path: /etc/sysconfig/jenkins
        regexp: '^JENKINS_PORT='
        line: 'JENKINS_PORT="1234"'
      notify:
        - Restart Jenkins

  handlers:
    - name: Restart Jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: restarted
